galaxy_info:
  role_name: instana
  author: bscp7
  description: Instana on Linux
  company: IBM
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - stretch
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal

  galaxy_tags:
    - monitoring
    - system
    - containers
    - docker
    - observability
    - server

dependencies: []
